version: "3.7"

services:

  # NATS-Server
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  # Gateway-MS
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    env_file:
      - .env
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
  
  # Products-MS
  products-ms:
    build: ./products-ms
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL: ${PRODUCTS_DATABASE_URL}
      - NATS_SERVERS: ${NATS_SERVERS}

  # Orders-MS
  orders-ms:
    build: ./orders-ms
    depends_on:
      - orders-db
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL: ${POSTGRES_DATABASE_URL}
      - NATS_SERVERS: ${NATS_SERVERS}
  
  # Orders Postgres DB
  orders-db:
    container_name: ${ORDERS_DB_CONTAINER_NAME}
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}